baseurl = "https://wews.co/"
title = "a blog of spaghettiwews"
author = "spaghettiwews"
canonifyurls = true
languagecode = "en"
theme = "hugo-novela"

[params]
  sitename = "a blog of spaghettiwews"
  description = "there is yet insufficient data for a meaningful answer"
  githubUsername = "spaghettiwews"
  tagline = "there is yet insufficient data for a meaningful answer"

[params.resume]
  link = "/page/resume"  

[permalinks]
  #post = "/:year/:month/:filename/"
  page = "/page/:title/"
